portfolio/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("projects/", include("projects.urls")),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = "projects"

urlpatterns = [
    path("", views.all_projects),
    path("<int:pk>", views.project_detail, name="project_detail"),  # int -> path converter
]

projects/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

projects/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.http import HttpResponse

from projects.models import Project

# Create your views here.
def all_projects(request):
    # query db to return all project objects
    projects = Project.objects.all()
    print(projects)
    return render(request, "projects/all_projects.html", {"projects": projects})


def project_detail(request, pk):
    # pk comes from urls file
    project = Project.objects.get(pk=pk)
    return render(request, "projects/detail.html", {"project": project})

projects/templates/projects/all_projects.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Projects</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
    <div class="container">
        <h1>Projects</h1>
        <div class="row">
        {% for project in projects %}
            <div class="col-md-4">
                <div class="card mb-2">
                    <img class="card-img-top" src="{% static project.image %}" alt="{{ project.description}}">
                    <div class="card-body">
                        <h5 class="card-title">{{ project.title }}</h5>
                        <p class="card-text">{{ project.description }}</p>
                        <a href="{% url "projects:project_detail" project.pk %}"
                        class="btn btn-primary">
                            Read More
                        </a>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </body>
</html>

projects/templates/projects/detail.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>

<body>
    <div class="container">
        <img 
        src="{% static project.image %}" 
        alt="{{ project.description }}
        width="200" 
        height="300""
        >
        <h1>{{ project.title }}</h1>
        <p>{{ project.description }}</p>
        <p>{{ project.technology }}</p>
</body>
</html>

projects/templates/projects/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    
</head>

<body>
    
    <div class="container">
        <h1>Formulário OLX</h1>
        <p> </p>
        <p> </p>
        <div class="row">
            <div class="col">
                <h3>Videogames</h3>
                    <p>2</p>
                <h3>Computadores e acessórios</h3>
                    <p>2</p>
                <h3>Celulares e Telefonia</h3>
                    <p>0</p>
                <h3>Áudio, TV e fotografia</h3>
                    <p>1</p>
            </div>
            <div class="col">
                <div class="form-group">
                    <label for="sel1">Escolha um Perfil:</label>
                    <select class="form-control" id="sel1">
                      <option>Perfil 1</option>
                      <option>Perfil 2</option>
                      <option>Perfil 3</option>
                      <option>Perfil 4</option>
                      <option>Perfil 5</option>
                      <option>Perfil 6</option>
                      <option>Perfil 7</option>
                      <option>Perfil 8</option>
                      <option>Perfil 9</option>
                      <option>Perfil 10</option>
                    </select>
                  </div>
                  <p> </p>
                  <p> </p>
                  <div class="form-group">
                    <label for="sel1">Escolha um CEP:</label>
                    <select class="form-control" id="sel1">
                      <option>Morada de Laranjeiras</option>
                      <option>Vitória</option>
                      <option>Vila Velha</option>
                    </select>
                  </div>
                  <p> </p>
                  <p> </p>
                  <button type="button" class="btn btn-primary btn-lg">Postar Produtos</button>
          </div>
        <div class="row">
          <div class="col">
            <h2>Falta Postar</h2>
            <div class="table-wrapper-scroll-y my-custom-scrollbar">

                <table class="table table-bordered table-striped mb-0">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Item</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td>Mouse</td>
                    </tr>
                    <tr>
                        <th scope="row">1</th>
                        <td>Teclado</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Monitor</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Headset</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Wii</td>
                      </tr>
                  </tbody>
                </table>
              
              </div>
              <p> </p>
              <p> </p>
            <button type="button" class="btn btn-primary btn-lg">Postar Agora</button>
            <button type="button" class="btn btn-secondary btn-lg">Não postar</button>
          </div>
          <div class="col">
            <h2>Não Postar</h2>
            <div class="table-wrapper-scroll-y my-custom-scrollbar">

                <table class="table table-bordered table-striped mb-0">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Item</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td>Mouse</td>
                    </tr>
                    <tr>
                        <th scope="row">1</th>
                        <td>Teclado</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Monitor</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Headset</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Wii</td>
                      </tr>
                  </tbody>
                </table>
              
              </div>
              <p> </p>
              <p> </p>
            <button type="button" class="btn btn-primary btn-lg">Postar</button>
          </div>
        </div>
        <div class="row">
          <div class="col">
            <h2>Postar agora</h2>
            <div class="table-wrapper-scroll-y my-custom-scrollbar">

                <table class="table table-bordered table-striped mb-0">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Item</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td>Mouse</td>
                    </tr>
                    <tr>
                        <th scope="row">1</th>
                        <td>Teclado</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Monitor</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Headset</td>
                      </tr>
                      <tr>

                      </tr>
                  </tbody>
                </table>
              
              </div>
              <p> </p>
              <p> </p>
            <button type="button" class="btn btn-primary btn-lg">Postar para postado</button>
          </div>
          <div class="col">
            <h2>Postados</h2>
            <div class="table-wrapper-scroll-y my-custom-scrollbar">

                <table class="table table-bordered table-striped mb-0">
                  <thead>
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Item</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <th scope="row">1</th>
                      <td>Mouse</td>
                    </tr>
                    <tr>
                        <th scope="row">1</th>
                        <td>Teclado</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Monitor</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Headset</td>
                      </tr>
                      <tr>
                        <th scope="row">1</th>
                        <td>Wii</td>
                      </tr>
                  </tbody>
                </table>
              
              </div>
              <p> </p>
              <p> </p>
            <button type="button" class="btn btn-primary btn-lg">Resetar Lista Postados</button>
          </div>
          
        </div>
        
      </div>


</body>
</html>